
volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge

services:

  db:
    container_name: mysql
    image: mysql:8.2.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinema
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "9090:8080"
    networks:
      - app-network

  back:
    container_name: laravel
    build:
      context: ./back
      dockerfile: Dockerfile
    working_dir: /var/www/
    volumes:
      - ./back:/var/www/
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      bash -c "composer install &&
               php artisan key:generate &&
               php artisan migrate:fresh --seed &&
               php artisan serve --host=0.0.0.0 --port=8000"
    networks:
      - app-network

  front:
    container_name: vue
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_BASE_URL=http://localhost:8000/api
    restart: unless-stopped
    command: >
      sh -c "npm install && npm run dev -- --host"
    networks:
      - app-network
